In [1]:
#Import Dependencies 
import pandas as pd
import geopandas as gp

In [2]:
#Set URL for Speed Record Scrape
speed_record_url = 'https://rcdb.com/rhr.htm?m=0'

speed_tables = pd.read_html(speed_record_url)

In [3]:
#Scrape Speed Record Table and save as a dataframe.
speed_record = speed_tables[1]
speed_record

,Rank,Speed,Roller Coaster,Amusement Park (Location),Opened
0,1st,149.1 mph,Formula Rossa,"Ferrari World Abu Dhabi (Abu Dhabi, Abu Dhabi,...",NaN
1,2nd,128 mph,Kingda Ka,"Six Flags Great Adventure (Jackson, New Jersey...",NaN
2,3rd,120 mph,Top Thrill Dragster,"Cedar Point (Sandusky, Ohio, United States)",NaN
3,4th,111.8 mph,Do-DodonpaRed Force,"Fuji-Q Highland (Fujiyoshida, Yamanashi, Japan...",NaN
4,5th,100 mph,Superman: Escape from Krypton,"Six Flags Magic Mountain (Valencia, California...",NaN
5,*,99.4 mph,Ring Racer,"NÃ¼rburgring (NÃ¼rburg, Rhineland-Palatinate, ...",NaN
6,6th,95 mph,Steel Dragon 2000Fury 325,"Nagashima Spa Land (Kuwana, Mie, Japan)Carowin...",NaN
7,7th,93 mph,Millennium Force,"Cedar Point (Sandusky, Ohio, United States)",NaN
8,8th,92 mph,Leviathan,"Canada's Wonderland (Vaughan, Ontario, Canada)",NaN
9,9th,91 mph,Orion,"Kings Island (Mason, Ohio, United States)",NaN
10,10th,90 mph,Intimidator 305,"Kings Dominion (Doswell, Virginia, United States)",NaN
11,*,*,Rankings are not assigned to roller coasters t...,Rankings are not assigned to roller coasters t...,Rankings are not assigned to roller coasters t...

In [4]:
#Drop unwanted Rows
speed_record = speed_record.drop(labels=[5,11], axis=0)

#Drop unwanted Column
speed_record = speed_record.drop(labels="Opened", axis=1)

speed_record

,Rank,Speed,Roller Coaster,Amusement Park (Location)
0,1st,149.1 mph,Formula Rossa,"Ferrari World Abu Dhabi (Abu Dhabi, Abu Dhabi,..."
1,2nd,128 mph,Kingda Ka,"Six Flags Great Adventure (Jackson, New Jersey..."
2,3rd,120 mph,Top Thrill Dragster,"Cedar Point (Sandusky, Ohio, United States)"
3,4th,111.8 mph,Do-DodonpaRed Force,"Fuji-Q Highland (Fujiyoshida, Yamanashi, Japan..."
4,5th,100 mph,Superman: Escape from Krypton,"Six Flags Magic Mountain (Valencia, California..."
6,6th,95 mph,Steel Dragon 2000Fury 325,"Nagashima Spa Land (Kuwana, Mie, Japan)Carowin..."
7,7th,93 mph,Millennium Force,"Cedar Point (Sandusky, Ohio, United States)"
8,8th,92 mph,Leviathan,"Canada's Wonderland (Vaughan, Ontario, Canada)"
9,9th,91 mph,Orion,"Kings Island (Mason, Ohio, United States)"
10,10th,90 mph,Intimidator 305,"Kings Dominion (Doswell, Virginia, United States)"

In [5]:
#Fix Data with Tied Record Holders
speed_fixes = [pd.Series(['4th', 111.8, 'Do-Dodonpa', 'Fuji-Q Highland (Fujiyoshida, Yamanashi, Japan)'], index=speed_record.columns),
                pd.Series(['4th', 111.8, 'Red Force', 'Ferrari Land (Salou, Tarragona, Catalonia, Spain)'], index=speed_record.columns),
                pd.Series(['6th', 95, 'Steel Dragon 2000', 'Nagashima Spa Land (Kuwana, Mie, Japan)'], index=speed_record.columns),
                pd.Series(['6th', 95, 'Fury 325', 'Carowinds (Charlotte, North Carolina, United States)'], index=speed_record.columns)]
speed_records_fixed = speed_record.append(speed_fixes,ignore_index=True)
speed_records_fixed

#Drop Rows with dirty data
speed_records_clean = speed_records_fixed.drop(labels=[3,5], axis=0)
speed_records_clean

,Rank,Speed,Roller Coaster,Amusement Park (Location)
0,1st,149.1 mph,Formula Rossa,"Ferrari World Abu Dhabi (Abu Dhabi, Abu Dhabi,..."
1,2nd,128 mph,Kingda Ka,"Six Flags Great Adventure (Jackson, New Jersey..."
2,3rd,120 mph,Top Thrill Dragster,"Cedar Point (Sandusky, Ohio, United States)"
4,5th,100 mph,Superman: Escape from Krypton,"Six Flags Magic Mountain (Valencia, California..."
6,7th,93 mph,Millennium Force,"Cedar Point (Sandusky, Ohio, United States)"
7,8th,92 mph,Leviathan,"Canada's Wonderland (Vaughan, Ontario, Canada)"
8,9th,91 mph,Orion,"Kings Island (Mason, Ohio, United States)"
9,10th,90 mph,Intimidator 305,"Kings Dominion (Doswell, Virginia, United States)"
10,4th,111.8,Do-Dodonpa,"Fuji-Q Highland (Fujiyoshida, Yamanashi, Japan)"
11,4th,111.8,Red Force,"Ferrari Land (Salou, Tarragona, Catalonia, Spain)"
12,6th,95.0,Steel Dragon 2000,"Nagashima Spa Land (Kuwana, Mie, Japan)"
13,6th,95.0,Fury 325,"Carowinds (Charlotte, North Carolina, United S..."

In [6]:
#Split the Amusement Park (Location) column & then Drop It
speed_records_clean[['Amusement Park','Location']] = speed_records_clean['Amusement Park (Location)'].str.split('(',expand=True)
speed_records_clean = speed_records_clean.drop(labels=['Amusement Park (Location)'], axis=1)
speed_records_clean

,Rank,Speed,Roller Coaster,Amusement Park,Location
0,1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,"Abu Dhabi, Abu Dhabi, United Arab Emirates)"
1,2nd,128 mph,Kingda Ka,Six Flags Great Adventure,"Jackson, New Jersey, United States)"
2,3rd,120 mph,Top Thrill Dragster,Cedar Point,"Sandusky, Ohio, United States)"
4,5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,"Valencia, California, United States)"
6,7th,93 mph,Millennium Force,Cedar Point,"Sandusky, Ohio, United States)"
7,8th,92 mph,Leviathan,Canada's Wonderland,"Vaughan, Ontario, Canada)"
8,9th,91 mph,Orion,Kings Island,"Mason, Ohio, United States)"
9,10th,90 mph,Intimidator 305,Kings Dominion,"Doswell, Virginia, United States)"
10,4th,111.8,Do-Dodonpa,Fuji-Q Highland,"Fujiyoshida, Yamanashi, Japan)"
11,4th,111.8,Red Force,Ferrari Land,"Salou, Tarragona, Catalonia, Spain)"
12,6th,95.0,Steel Dragon 2000,Nagashima Spa Land,"Kuwana, Mie, Japan)"
13,6th,95.0,Fury 325,Carowinds,"Charlotte, North Carolina, United States)"

In [7]:
#Split the Location into City, State, Country, Etc. 
speed_records_clean[['City', 'State', 'Country1', 'Extra']] = speed_records_clean['Location'].str.split(',', expand=True)
speed_records_clean

,Rank,Speed,Roller Coaster,Amusement Park,Location,City,State,Country1,Extra
0,1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,"Abu Dhabi, Abu Dhabi, United Arab Emirates)",Abu Dhabi,Abu Dhabi,United Arab Emirates),None
1,2nd,128 mph,Kingda Ka,Six Flags Great Adventure,"Jackson, New Jersey, United States)",Jackson,New Jersey,United States),None
2,3rd,120 mph,Top Thrill Dragster,Cedar Point,"Sandusky, Ohio, United States)",Sandusky,Ohio,United States),None
4,5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,"Valencia, California, United States)",Valencia,California,United States),None
6,7th,93 mph,Millennium Force,Cedar Point,"Sandusky, Ohio, United States)",Sandusky,Ohio,United States),None
7,8th,92 mph,Leviathan,Canada's Wonderland,"Vaughan, Ontario, Canada)",Vaughan,Ontario,Canada),None
8,9th,91 mph,Orion,Kings Island,"Mason, Ohio, United States)",Mason,Ohio,United States),None
9,10th,90 mph,Intimidator 305,Kings Dominion,"Doswell, Virginia, United States)",Doswell,Virginia,United States),None
10,4th,111.8,Do-Dodonpa,Fuji-Q Highland,"Fujiyoshida, Yamanashi, Japan)",Fujiyoshida,Yamanashi,Japan),None
11,4th,111.8,Red Force,Ferrari Land,"Salou, Tarragona, Catalonia, Spain)",Salou,Tarragona,Catalonia,Spain)
12,6th,95.0,Steel Dragon 2000,Nagashima Spa Land,"Kuwana, Mie, Japan)",Kuwana,Mie,Japan),None
13,6th,95.0,Fury 325,Carowinds,"Charlotte, North Carolina, United States)",Charlotte,North Carolina,United States),None

In [8]:
#Dop Location Column
speed_records_clean = speed_records_clean.drop(labels=['Location'], axis=1)
speed_records_clean

,Rank,Speed,Roller Coaster,Amusement Park,City,State,Country1,Extra
0,1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates),None
1,2nd,128 mph,Kingda Ka,Six Flags Great Adventure,Jackson,New Jersey,United States),None
2,3rd,120 mph,Top Thrill Dragster,Cedar Point,Sandusky,Ohio,United States),None
4,5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,Valencia,California,United States),None
6,7th,93 mph,Millennium Force,Cedar Point,Sandusky,Ohio,United States),None
7,8th,92 mph,Leviathan,Canada's Wonderland,Vaughan,Ontario,Canada),None
8,9th,91 mph,Orion,Kings Island,Mason,Ohio,United States),None
9,10th,90 mph,Intimidator 305,Kings Dominion,Doswell,Virginia,United States),None
10,4th,111.8,Do-Dodonpa,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan),None
11,4th,111.8,Red Force,Ferrari Land,Salou,Tarragona,Catalonia,Spain)
12,6th,95.0,Steel Dragon 2000,Nagashima Spa Land,Kuwana,Mie,Japan),None
13,6th,95.0,Fury 325,Carowinds,Charlotte,North Carolina,United States),None

In [9]:
#Remove ) from Country 1
speed_records_clean['Country1'] = speed_records_clean['Country1'].str[:-1]
speed_records_clean

,Rank,Speed,Roller Coaster,Amusement Park,City,State,Country1,Extra
0,1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates,None
1,2nd,128 mph,Kingda Ka,Six Flags Great Adventure,Jackson,New Jersey,United States,None
2,3rd,120 mph,Top Thrill Dragster,Cedar Point,Sandusky,Ohio,United States,None
4,5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,Valencia,California,United States,None
6,7th,93 mph,Millennium Force,Cedar Point,Sandusky,Ohio,United States,None
7,8th,92 mph,Leviathan,Canada's Wonderland,Vaughan,Ontario,Canada,None
8,9th,91 mph,Orion,Kings Island,Mason,Ohio,United States,None
9,10th,90 mph,Intimidator 305,Kings Dominion,Doswell,Virginia,United States,None
10,4th,111.8,Do-Dodonpa,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan,None
11,4th,111.8,Red Force,Ferrari Land,Salou,Tarragona,Cataloni,Spain)
12,6th,95.0,Steel Dragon 2000,Nagashima Spa Land,Kuwana,Mie,Japan,None
13,6th,95.0,Fury 325,Carowinds,Charlotte,North Carolina,United States,None

In [10]:
#Fix Country1 Column Data
speed_records_clean["Country1"] = speed_records_clean["Country1"].str.replace("Cataloni","Spain")
speed_records_clean

,Rank,Speed,Roller Coaster,Amusement Park,City,State,Country1,Extra
0,1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates,None
1,2nd,128 mph,Kingda Ka,Six Flags Great Adventure,Jackson,New Jersey,United States,None
2,3rd,120 mph,Top Thrill Dragster,Cedar Point,Sandusky,Ohio,United States,None
4,5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,Valencia,California,United States,None
6,7th,93 mph,Millennium Force,Cedar Point,Sandusky,Ohio,United States,None
7,8th,92 mph,Leviathan,Canada's Wonderland,Vaughan,Ontario,Canada,None
8,9th,91 mph,Orion,Kings Island,Mason,Ohio,United States,None
9,10th,90 mph,Intimidator 305,Kings Dominion,Doswell,Virginia,United States,None
10,4th,111.8,Do-Dodonpa,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan,None
11,4th,111.8,Red Force,Ferrari Land,Salou,Tarragona,Spain,Spain)
12,6th,95.0,Steel Dragon 2000,Nagashima Spa Land,Kuwana,Mie,Japan,None
13,6th,95.0,Fury 325,Carowinds,Charlotte,North Carolina,United States,None

In [11]:
#Drop Extra Column and create Final Dataframe
speed_records_final = speed_records_clean.drop(labels=['Extra'], axis=1)
speed_records_final = speed_records_final.rename(columns={'Country1': 'Country'})
speed_records_final

,Rank,Speed,Roller Coaster,Amusement Park,City,State,Country
0,1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates
1,2nd,128 mph,Kingda Ka,Six Flags Great Adventure,Jackson,New Jersey,United States
2,3rd,120 mph,Top Thrill Dragster,Cedar Point,Sandusky,Ohio,United States
4,5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,Valencia,California,United States
6,7th,93 mph,Millennium Force,Cedar Point,Sandusky,Ohio,United States
7,8th,92 mph,Leviathan,Canada's Wonderland,Vaughan,Ontario,Canada
8,9th,91 mph,Orion,Kings Island,Mason,Ohio,United States
9,10th,90 mph,Intimidator 305,Kings Dominion,Doswell,Virginia,United States
10,4th,111.8,Do-Dodonpa,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan
11,4th,111.8,Red Force,Ferrari Land,Salou,Tarragona,Spain
12,6th,95.0,Steel Dragon 2000,Nagashima Spa Land,Kuwana,Mie,Japan
13,6th,95.0,Fury 325,Carowinds,Charlotte,North Carolina,United States

In [12]:
#Read in the Speed_Cities GeoJSON
speed_cities = gp.read_file('geojsons/speed_cities.geojson')
speed_cities

           City                     geometry
0     Abu Dhabi    POINT (54.37408 24.47715)
1       Jackson   POINT (-74.42928 40.13295)
2      Sandusky   POINT (-82.70645 41.45019)
3   Fujiyoshida   POINT (138.83337 35.48122)
4         Salou     POINT (1.14378 41.07702)
5      Valencia  POINT (-118.56128 34.41396)
6        Kuwana   POINT (136.64967 35.04827)
7     Charlotte   POINT (-80.84358 35.22936)
8      Sandusky   POINT (-82.71031 41.45019)
9       Vaughan   POINT (-79.50874 43.82140)
10        Mason   POINT (-84.30925 39.36032)
11      Doswell   POINT (-77.46460 37.86022)

In [13]:
#Merge the two dataframes
speed_records = speed_cities.merge(speed_records_final, on='City')
speed_records

,City,geometry,Rank,Speed,Roller Coaster,Amusement Park,State,Country
0,Abu Dhabi,POINT (54.37408 24.47715),1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,United Arab Emirates
1,Jackson,POINT (-74.42928 40.13295),2nd,128 mph,Kingda Ka,Six Flags Great Adventure,New Jersey,United States
2,Sandusky,POINT (-82.70645 41.45019),3rd,120 mph,Top Thrill Dragster,Cedar Point,Ohio,United States
3,Sandusky,POINT (-82.70645 41.45019),7th,93 mph,Millennium Force,Cedar Point,Ohio,United States
4,Sandusky,POINT (-82.71031 41.45019),3rd,120 mph,Top Thrill Dragster,Cedar Point,Ohio,United States
5,Sandusky,POINT (-82.71031 41.45019),7th,93 mph,Millennium Force,Cedar Point,Ohio,United States
6,Fujiyoshida,POINT (138.83337 35.48122),4th,111.8,Do-Dodonpa,Fuji-Q Highland,Yamanashi,Japan
7,Salou,POINT (1.14378 41.07702),4th,111.8,Red Force,Ferrari Land,Tarragona,Spain
8,Valencia,POINT (-118.56128 34.41396),5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,California,United States
9,Kuwana,POINT (136.64967 35.04827),6th,95.0,Steel Dragon 2000,Nagashima Spa Land,Mie,Japan
10,Charlotte,POINT (-80.84358 35.22936),6th,95.0,Fury 325,Carowinds,North Carolina,United States
11,Vaughan,POINT (-79.50874 43.82140),8th,92 mph,Leviathan,Canada's Wonderland,Ontario,Canada
12,Mason,POINT (-84.30925 39.36032),9th,91 mph,Orion,Kings Island,Ohio,United States
13,Doswell,POINT (-77.46460 37.86022),10th,90 mph,Intimidator 305,Kings Dominion,Virginia,United States

In [14]:
#Drop Duplicate Rows
speed_records = speed_records.drop(labels=[3,4], axis=0)
speed_records = speed_records.reset_index(drop=True)
speed_records

,City,geometry,Rank,Speed,Roller Coaster,Amusement Park,State,Country
0,Abu Dhabi,POINT (54.37408 24.47715),1st,149.1 mph,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,United Arab Emirates
1,Jackson,POINT (-74.42928 40.13295),2nd,128 mph,Kingda Ka,Six Flags Great Adventure,New Jersey,United States
2,Sandusky,POINT (-82.70645 41.45019),3rd,120 mph,Top Thrill Dragster,Cedar Point,Ohio,United States
5,Sandusky,POINT (-82.71031 41.45019),7th,93 mph,Millennium Force,Cedar Point,Ohio,United States
6,Fujiyoshida,POINT (138.83337 35.48122),4th,111.8,Do-Dodonpa,Fuji-Q Highland,Yamanashi,Japan
7,Salou,POINT (1.14378 41.07702),4th,111.8,Red Force,Ferrari Land,Tarragona,Spain
8,Valencia,POINT (-118.56128 34.41396),5th,100 mph,Superman: Escape from Krypton,Six Flags Magic Mountain,California,United States
9,Kuwana,POINT (136.64967 35.04827),6th,95.0,Steel Dragon 2000,Nagashima Spa Land,Mie,Japan
10,Charlotte,POINT (-80.84358 35.22936),6th,95.0,Fury 325,Carowinds,North Carolina,United States
11,Vaughan,POINT (-79.50874 43.82140),8th,92 mph,Leviathan,Canada's Wonderland,Ontario,Canada
12,Mason,POINT (-84.30925 39.36032),9th,91 mph,Orion,Kings Island,Ohio,United States
13,Doswell,POINT (-77.46460 37.86022),10th,90 mph,Intimidator 305,Kings Dominion,Virginia,United States