In [1]:
#Import Dependencies 
import pandas as pd
import geopandas as gp

In [2]:
#Set URL for Speed Record Scrape
speed_record_url = 'https://rcdb.com/rhr.htm?m=0'

speed_tables = pd.read_html(speed_record_url)

In [4]:
#Scrape Speed Record Table and save as a dataframe.
speed_record = speed_tables[1]
speed_record

,Rank,Speed,Roller Coaster,Amusement Park (Location),Opened
0,1st,149.1 mph,Formula Rossa,"Ferrari World Abu Dhabi (Abu Dhabi, Abu Dhabi,...",NaN
1,2nd,128 mph,Kingda Ka,"Six Flags Great Adventure (Jackson, New Jersey...",NaN
2,3rd,120 mph,Top Thrill Dragster,"Cedar Point (Sandusky, Ohio, United States)",NaN
3,4th,111.8 mph,Do-DodonpaRed Force,"Fuji-Q Highland (Fujiyoshida, Yamanashi, Japan...",NaN
4,5th,100 mph,Superman: Escape from Krypton,"Six Flags Magic Mountain (Valencia, California...",NaN
5,*,99.4 mph,Ring Racer,"NÃ¼rburgring (NÃ¼rburg, Rhineland-Palatinate, ...",NaN
6,6th,95 mph,Steel Dragon 2000Fury 325,"Nagashima Spa Land (Kuwana, Mie, Japan)Carowin...",NaN
7,7th,93 mph,Millennium Force,"Cedar Point (Sandusky, Ohio, United States)",NaN
8,8th,92 mph,Leviathan,"Canada's Wonderland (Vaughan, Ontario, Canada)",NaN
9,9th,91 mph,Orion,"Kings Island (Mason, Ohio, United States)",NaN
10,10th,90 mph,Intimidator 305,"Kings Dominion (Doswell, Virginia, United States)",NaN
11,*,*,Rankings are not assigned to roller coasters t...,Rankings are not assigned to roller coasters t...,Rankings are not assigned to roller coasters t...

In [7]:
#Drop unwanted Rows
#speed_record = speed_record.drop(labels=[5,11], axis=0)

#Drop unwanted Column
speed_record = speed_record.drop(labels="Opened", axis=1)

speed_record

,Rank,Speed,Roller Coaster,Amusement Park (Location)
0,1st,149.1 mph,Formula Rossa,"Ferrari World Abu Dhabi (Abu Dhabi, Abu Dhabi,..."
1,2nd,128 mph,Kingda Ka,"Six Flags Great Adventure (Jackson, New Jersey..."
2,3rd,120 mph,Top Thrill Dragster,"Cedar Point (Sandusky, Ohio, United States)"
3,4th,111.8 mph,Do-DodonpaRed Force,"Fuji-Q Highland (Fujiyoshida, Yamanashi, Japan..."
4,5th,100 mph,Superman: Escape from Krypton,"Six Flags Magic Mountain (Valencia, California..."
6,6th,95 mph,Steel Dragon 2000Fury 325,"Nagashima Spa Land (Kuwana, Mie, Japan)Carowin..."
7,7th,93 mph,Millennium Force,"Cedar Point (Sandusky, Ohio, United States)"
8,8th,92 mph,Leviathan,"Canada's Wonderland (Vaughan, Ontario, Canada)"
9,9th,91 mph,Orion,"Kings Island (Mason, Ohio, United States)"
10,10th,90 mph,Intimidator 305,"Kings Dominion (Doswell, Virginia, United States)"

In [10]:
speed_record[['Amusement Park','Location']] = speed_record['Amusement Park (Location)'].str.split('(',expand=True)
speed_record

ValueError: Columns must be same length as key